# Generated by Django 3.0.3 on 2020-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_auto_20200402_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$K3iEqG9bzakS$s/fRuQPLcb1k7CkLKn0Jiop4SOlpyHPz3hSartmrZjQ=', max_length=128, verbose_name='password'),
        ),
    ]
