# Generated by Django 3.0.3 on 2020-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_auto_20200506_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$H38PSyO7ellF$0DvKofABwNG+krnCt7Zo1YqVG6axwURFmdEa4lvBLzs=', max_length=128, verbose_name='password'),
        ),
    ]
