# Generated by Django 3.0.3 on 2020-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_auto_20200506_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$uRvRM1ecDzWV$UmcqI3pRi2PEmbUjFcDenYfaqymTApBmpWnbvyx7R20=', max_length=128, verbose_name='password'),
        ),
    ]
