# Generated by Django 3.0.3 on 2020-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0013_auto_20200506_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$cAMOdwLr6tpD$0w3J4mbTVm4Mf3lKM7hMPKGdB3pM8XR0e3RM7OF6jZI=', max_length=128, verbose_name='password'),
        ),
    ]
