# Generated by Django 3.0.3 on 2020-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0014_auto_20200506_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$EqSnlMwxRbQ1$+T7BQOYiE0vzflYKMyqeKLQW3yloTbEHHDW0ttBB+2s=', max_length=128, verbose_name='password'),
        ),
    ]
