# Generated by Django 3.0.3 on 2020-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0015_auto_20200506_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$TONYhgRb8lbH$5dnunyL7c/TiiX6EZAmW1PjdX3MFEpAFz6eGhu+7MHc=', max_length=128, verbose_name='password'),
        ),
    ]
