# Generated by Django 3.0.3 on 2020-05-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0016_auto_20200506_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$O1K4Y9j2oIcH$5rsLmYJJSKn0Xv3kYmELWbJywkNDwiKnXGMlYzed5m4=', max_length=128, verbose_name='password'),
        ),
    ]
