# Generated by Django 3.0.3 on 2020-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0017_auto_20200508_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$180000$ZDhI3Ph2Q9uf$mUXLqNNFPcOdvcjwBzgXw7Ww/aDfjZPCXk72QkOkGFk=', max_length=128, verbose_name='password'),
        ),
    ]
